config/routes.rb
Rails.application.routes.draw do
  get 'events/index'

  get 'events/show'

  devise_for :admin_users, ActiveAdmin::Devise.config
  get 'dashboards/index'

  get 'logins/index'
  
  root 'events#index'

  ActiveAdmin.routes(self)
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/event.rb
class Event < ActiveRecord::Base
    def index
        @events = Event.order('id desc').all
    end
    
    scope :past_events,->{ where('date < ?', Date.today) }
    scope :future_events,->{ where('date > ?', Date.today) }
    scope :ongoing_events,->{ where('date == ?', Date.today) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
  end
  
  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to events_path, :notice => "Event Successfully Created"
    else
      render "new"
    end
  end
  
  private
  def event_params
    params.require(:event).permit(:title, :description, :venue, :date, :start_time, :end_time, :ticket_price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/views/dashboards/index.html.erb
<h1>Dashboards#index</h1>
<p>Find me in app/views/dashboards/index.html.erb</p>

app/views/events/index.html.erb
<div class="container">
    <h3> Here will be some info about AGPCC and a photo album</h3>
</div>
<br><br><br>
<div class="container">
    <h3>If you are the admin then login here</h3><br>
    <button type="button" class="btn btn-default"><%= link_to "Admin Login", admin_root_path %></button>
</div>
<br><br><br>
<div class="container">
    <h4>List of Events</h4>
    <table class="table table-hover">
    <thead>
      <tr>
        <th>Event Title</th>
        <th>Venue</th>
        <th>Date</th>
        <th>Start Time</th>
        <th>End Time</th>
        <th>Ticket Price</th>
      </tr>
    </thead>
    <tbody>
      <% @events.each do |event| %> 
          <tr>
            <td><%= event.title %></td>
            <td><%= event.venue %></td>
            <td><%= event.date %></td>
            <td><%= event.start_time %></td>
            <td><%= event.end_time %></td>
            <td><%= event.ticket_price %></td>
          </tr>
      <% end %>
    </tbody>
    
</div>

app/views/events/show.html.erb
<h1>Events#show</h1>
<p>Find me in app/views/events/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AGPCC Check-In System</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="/public/css/main.css">
</head>
<body>
    <nav class="navbar navbar-default maroon">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">AGPCC</a>
            </div>
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Home</a></li>
                <li><a href="#">Page 1</a></li>
                <li><a href="#">Page 2</a></li> 
                <li><a href="#">Page 3</a></li> 
            </ul>
        </div>
    </nav>

<%= yield %>

</body>
</html>